-- ============================================================================
-- Migration 045 — Supabase Storage bucket for AI-generated social media images
-- ============================================================================
--
-- Posts on Facebook / Telegram / Instagram get 5-10x more engagement when
-- they include a relevant image. The Social Growth Suite (mig 043) already
-- supports media_urls on social_posts — what was missing is a place to
-- store the AI-generated bytes so platforms can fetch them.
--
-- This migration:
--   1) Creates a PUBLIC bucket `social-media` (Facebook / Telegram need a
--      publicly fetchable URL when posting; we can't ship a signed-URL
--      flow because their cache workers ignore Authorization headers).
--   2) Adds RLS policies so only authenticated super-admins can upload /
--      delete, but anyone can READ (which is what "public" implies).
--
-- IMPORTANT: Supabase Storage bucket DDL must run as the postgres role
-- (which it does in Supabase SQL Editor by default). If running via psql
-- as a non-superuser, prepend `set role postgres;`.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) Create the bucket. on conflict (id) do nothing keeps this idempotent.
-- ----------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'social-media',
  'social-media',
  true,                                  -- public reads (required for FB/TG)
  10485760,                              -- 10 MB per file
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public                = excluded.public,
  file_size_limit       = excluded.file_size_limit,
  allowed_mime_types    = excluded.allowed_mime_types;


-- ----------------------------------------------------------------------------
-- 2) RLS policies. Storage uses the storage.objects table internally.
-- ----------------------------------------------------------------------------
-- Drop old policies if they exist (idempotent re-run)
drop policy if exists "social_media_public_read"   on storage.objects;
drop policy if exists "social_media_admin_write"   on storage.objects;
drop policy if exists "social_media_admin_update"  on storage.objects;
drop policy if exists "social_media_admin_delete"  on storage.objects;


-- PUBLIC READ — any caller (including FB / TG bots fetching the URL)
-- can GET an image from this bucket. This is the whole point of a
-- public bucket; without it, social platforms 403 on the fetch.
create policy "social_media_public_read"
on storage.objects for select
using (bucket_id = 'social-media');


-- WRITE — only super-admins can upload. The Social Suite is super-admin
-- only anyway, so this matches the application-level gate.
create policy "social_media_admin_write"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'social-media'
  and exists (
    select 1 from public.super_admins where user_id = auth.uid()
  )
);


-- UPDATE — super-admin only (rename, move, etc.)
create policy "social_media_admin_update"
on storage.objects for update
to authenticated
using (
  bucket_id = 'social-media'
  and exists (
    select 1 from public.super_admins where user_id = auth.uid()
  )
)
with check (
  bucket_id = 'social-media'
  and exists (
    select 1 from public.super_admins where user_id = auth.uid()
  )
);


-- DELETE — super-admin only
create policy "social_media_admin_delete"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'social-media'
  and exists (
    select 1 from public.super_admins where user_id = auth.uid()
  )
);


-- ----------------------------------------------------------------------------
-- Reload PostgREST cache (cheap, useful while iterating)
-- ----------------------------------------------------------------------------
notify pgrst, 'reload schema';
